DROP TABLE STUDENT;

CREATE TABLE STUDENT(Fname VARCHAR2(25), Subject VARCHAR2(25), MARKS NUMBER);

INSERT INTO STUDENT VALUES ('SARIKA','JAVASCRIPT',49);
INSERT INTO STUDENT VALUES ('SOMESH','PYTHON',92);
INSERT INTO STUDENT VALUES ('SHASHANK','PYTHON',29);
INSERT INTO STUDENT VALUES ('MONTY','PYTHON',38);
INSERT INTO STUDENT VALUES ('MITHILESH','PYTHON',26);
INSERT INTO STUDENT VALUES ('AKASH','PYTHON',10);
INSERT INTO STUDENT VALUES ('VEDANT','PYTHON',30);
INSERT INTO STUDENT VALUES ('AJAY','PYTHON',52);

SELECT * FROM STUDENT;

SELECT SUBJECT, MARKS*2 FROM STUDENT;
SELECT SUBJECT,MARKS, MARKS-10 FROM STUDENT;
SELECT 100-20 FROM DUAL;
SELECT SUBJECT, MARKS, MARKS/2 FROM STUDENT;