--RELATIONAL & COMPARISION OPERATOR
--(=,<,>,>=,<=,<>,!=,^=)

SELECT * FROM STUDENT;
SELECT * FROM STUDENT WHERE marks = 30;
SELECT * FROM STUDENT WHERE subject = 'PYTHON';

SELECT * FROM STUDENT WHERE marks<89;
SELECT * FROM STUDENT WHERE marks>89;

SELECT * FROM STUDENT WHERE marks>= 50;
SELECT * FROM STUDENT WHERE marks<=50;

--SELECT 110<35 FROM DUAL;
--SELECT 250=250 FROM DUAL;

--not equal to
SELECT * FROM STUDENT WHERE marks<> 92;
SELECT * FROM STUDENT WHERE marks != 92;
SELECT * FROM STUDENT WHERE marks ^= 92;


--LOGICAL OPERATORS
--(AND,OR,NOT)
--AND
SELECT * FROM STUDENT WHERE MARKS = 92 AND SUBJECT = 'PYTHON';

SELECT * FROM STUDENT WHERE subject ='PYTHON' AND marks = 52;

SELECT * FROM STUDENT WHERE subject='JAVASCRIPT' AND marks=49;

SELECT * FROM STUDENT WHERE subject='PYTHON' AND marks=52;

--OR

SELECT * FROM STUDENT WHERE marks = 92 OR subject = 'PYTHON';

SELECT * FROM STUDENT WHERE subject = 'PYTHON' OR fname = 'AJAY';

SELECT * FROM STUDENT WHERE subject = 'JAVASCRIPT' OR marks = 92;

--SELECT * FROM STUDENT WHERE subject = 'PYTHON' OR marks = 92 AND;

--NOT

SELECT * FROM STUDENT WHERE marks = 92;

SELECT * FROM STUDENT WHERE NOT marks = 92;

SELECT * FROM STUDENT WHERE marks NOT IN (92);

------------------------------------------------------------------

--BETWEEN AND OPERATORS

--SELECT * FROM STUDENT WHERE marks = 52 AND MARKS = 92 AND marks = 30;

--SELECT * FROM STUDENT WHERE MARKS IN (26,27,28,29....;

SELECT * FROM STUDENT WHERE marks BETWEEN 25 AND 50;

SELECT * FROM STUDENT WHERE marks NOT BETWEEN 25 AND 50;

SELECT * FROM STUDENT WHERE subject BETWEEN 'JAVASCRIPT' AND 'PYTHON';

