--ORDER BY
select * from vendors;

select * from vendors order by VENDOR_NAME;
SELECT * FROM VENDORS ORder by VENDOR_ID;
SELECT * FROM VENDORS ORder by VENDOR_COUNTRY;

--sorting with ASC & DESC keyword
SELECT * FROM VENDORS ORDER BY VENDOR_NAME ASC;
SELECT * FROM VENDORS ORDER BY VENDOR_COUNTRY DESC;
SELECT * FROM VENDORS ORDER BY VENDOR_PRICE DESC;
SELECT * FROM VENDORS ORDER BY VENDOR_COUNTRY DESC;

--sorting with ASC & DESC keyword ON MULTI COLUMNS
select VENDOR_NAME, VENDOR_COUNTRY from vendors order by VENDOR_NAME, VENDOR_COUNTRY desc;
SELECT VENDOR_NAME, VENDOR_COUNTRY FROM VENDORS ORDER BY VENDOR_NAME DESC, VENDOR_COUNTRY DESC;
SELECT VENDOR_NAME, VENDOR_COUNTRY FROM VENDORS ORDER BY VENDOR_NAME DESC, VENDOR_COUNTRY ASC;

--SORTING USING COLUMNS
SELECT VENDOR_ID, VENDOR_NAME, VENDOR_COUNTRY FROM VENDORS ORDER BY vendor_price DESC;
SELECT VENDOR_PRICE, VENDOR_NAME, VENDOR_COUNTRY FROM VENDORS ORDER BY vendor_id ASC;
SELECT VENDOR_ID, VENDOR_NAME, VENDOR_COUNTRY, VENDOR_PRICE FROM VENDORS ORDER BY VENDOR_PRICE DESC;

--SORTING USING EXP
SELECT LENGTH('SQL') FROM DUAL;
SELECT VENDOR_NAME, LENGTH(VENDOR_NAME) FROM VENDORS;
SELECT VENDOR_ID, VENDOR_NAME, VENDOR_COUNTRY, VENDOR_PRICE, LENGTH(VENDOR_COUNTRY) FROM VENDORS
ORDER BY LENGTH(vendor_country) DESC;

--SORTING USING COLUMN POSITIONS
SELECT VENDOR_NAME, VENDOR_COUNTRY, VENDOR_PRICE FROM VENDORS
ORDER BY 1 DESC;
SELECT VENDOR_COUNTRY, VENDOR_NAME, VENDOR_PRICE FROM VENDORS
ORDER BY 1 DESC;
SELECT VENDOR_COUNTRY, VENDOR_NAME, VENDOR_PRICE FROM VENDORS
ORDER BY 2 DESC;
SELECT VENDOR_COUNTRY, VENDOR_NAME, VENDOR_PRICE FROM VENDORS
ORDER BY 3 DESC;
SELECT VENDOR_COUNTRY, VENDOR_NAME, VENDOR_PRICE FROM VENDORS
ORDER BY 1, 2 DESC;
SELECT VENDOR_COUNTRY, VENDOR_NAME, VENDOR_PRICE FROM VENDORS
ORDER BY VENDOR_COUNTRY, VENDOR_NAME, VENDOR_PRICE DESC;
DESC VENDORS;


--Sorting with null values
SELECT VENDOR_ID, VENDOR_NAME, VENDOR_COUNTRY FROM VENDORS ORDER BY VENDOR_NAME DESC;
SELECT VENDOR_ID, VENDOR_NAME, VENDOR_COUNTRY FROM VENDORS ORDER BY VENDOR_NAME ASC;

SELECT VENDOR_ID, VENDOR_NAME, VENDOR_COUNTRY FROM VENDORS ORDER BY VENDOR_NAME ASC NULLS FIRST;

SELECT VENDOR_ID, VENDOR_NAME, VENDOR_COUNTRY FROM VENDORS ORDER BY VENDOR_NAME ASC NULLS LAST;
select VENDOR_ID,VENDOR_NAME, VENDOR_COUNTRY from vendors order by VENDOR_NAME asc;

select VENDOR_ID,VENDOR_NAME, VENDOR_COUNTRY from vendors order by VENDOR_NAME DESC NULLS FIRST;
select VENDOR_ID,VENDOR_NAME, VENDOR_COUNTRY from vendors order by VENDOR_NAME DESC;

select VENDOR_ID,VENDOR_NAME, VENDOR_COUNTRY from vendors order by VENDOR_NAME desc NULLS LAST;











