--GROUP BY
SELECT * FROM EMPLOYEES;

--UNIQUE VAL
SELECT DISTINCT DEPARTMENT_ID FROM EMPLOYEES;

SELECT DEPARTMENT_ID FROM EMPLOYEES GROUP BY DEPARTMENT_ID;

--RULE GROUP BY
--SELECT EMPLOYEE_ID,DEPARTMENT_ID FROM EMPLOYEES GROUP BY DEPARTMENT_ID;
SELECT EMPLOYEE_ID, DEPARTMENT_ID FROM EMPLOYEES GROUP BY EMPLOYEE_ID, DEPARTMENT_ID;
SELECT EMPLOYEE_ID FROM EMPLOYEES GROUP BY EMPLOYEE_ID,DEPARTMENT_ID;

--GROUP BY USING AGGREG FUN
SELECT JOB_ID, COUNT(EMPLOYEE_ID) FROM EMPLOYEES GROUP BY JOB_ID;
SELECT HIRE_DATE, COUNT(EMPLOYEE_ID) FROM EMPLOYEES GROUP BY HIRE_DATE;
SELECT DEPARTMENT_ID, MIN(SALARY), MAX(SALARY) FROM EMPLOYEES GROUP BY DEPARTMENT_ID;

--GROUP BY CLAUSE USING EXPRESSION
SELECT HIRE_DATE,EXTRACT(YEAR FROM HIRE_DATE) FROM EMPLOYEES;

SELECT EXTRACT(YEAR FROM HIRE_DATE) FROM EMPLOYEES
GROUP BY EXTRACT(YEAR FROM HIRE_DATE)

